### ISSUE TITLE
function and class objects

### ISSUE THREAD

**Issue by cmlaverdiere** [wbolster/evil-text-object-python#3]
Hi, have you considered implementing other common python text objects like functions and classes? I've been a heavy user of [this](https://github.com/bps/vim-textobj-python) in the past, and it's really handy.

**Comment by wbolster** [comment]
yeah, good idea. i did think about that briefly (hence the generic package name) but since python code is structured using indentation, https://github.com/TheBB/evil-indent-plus already covers many of the use cases.

if you figure out which of the existing `python-nav-...` building blocks can be used here, that would be nice.

**Comment by talwrii** [comment]
I have implemented this for functions.

See #4

**Comment by wbolster** [comment]
awesome, i will have a look later!

**Comment by wbolster** [comment]
see #4
